[package]
name = "devbot"
version = "0.1.0"
edition = "2021"

[dependencies]
descord = { git = "https://github.com/DescordLib/descord", version = "0.1.10" }
dotenvy = "0.15.7"
env_logger = "0.11.5"
lazy_static = "1.5.0"
tokio = { version = "1.36.0", features = ["full"] }
